"""updated sessions_fact table to correctly state type of foreign key columns

Revision ID: fc50064b24af
Revises: ff596e66442c
Create Date: 2024-03-03 12:04:55.701847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc50064b24af'
down_revision = 'ff596e66442c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions_fact', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'date_dimension', ['date_key'], ['date_key'])
        batch_op.create_foreign_key(None, 'user_dimension', ['user_key'], ['user_key'])
        batch_op.create_foreign_key(None, 'time_dimension', ['time_key'], ['time_key'])
        batch_op.create_foreign_key(None, 'poker_table_dimension', ['table_key'], ['table_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions_fact', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
