"""first full db

Revision ID: ff596e66442c
Revises: 0902f5ef3537
Create Date: 2024-03-03 11:50:27.483148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff596e66442c'
down_revision = '0902f5ef3537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date_dimension',
    sa.Column('date_key', sa.SmallInteger(), nullable=False),
    sa.Column('full_date', sa.Date(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('day_num_in_month', sa.SmallInteger(), nullable=False),
    sa.Column('day_num_overall', sa.SmallInteger(), nullable=False),
    sa.Column('day_name', sa.String(length=9), nullable=False),
    sa.Column('day_abbrev', sa.CHAR(length=3), nullable=False),
    sa.Column('weekday_flag', sa.CHAR(length=1), nullable=False),
    sa.Column('week_num_in_year', sa.SmallInteger(), nullable=False),
    sa.Column('week_num_overall', sa.SmallInteger(), nullable=False),
    sa.Column('week_begin_date', sa.Date(), nullable=False),
    sa.Column('week_begin_date_key', sa.SmallInteger(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('month_num_overall', sa.SmallInteger(), nullable=False),
    sa.Column('month_name', sa.String(length=9), nullable=False),
    sa.Column('month_abbrev', sa.CHAR(length=3), nullable=False),
    sa.Column('quarter', sa.SmallInteger(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('yearmo', sa.Integer(), nullable=False),
    sa.Column('last_day_in_month_flag', sa.CHAR(length=1), nullable=False),
    sa.Column('same_day_year_ago_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('date_key')
    )
    op.create_table('room_dimension',
    sa.Column('room_key', sa.Integer(), nullable=False),
    sa.Column('room_name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('state_province', sa.String(length=100), nullable=False),
    sa.Column('state_province_code', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('room_key')
    )
    op.create_table('sessions_fact',
    sa.Column('user_key', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('table_key', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('date_key', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('time_key', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('buy_in', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cash_out', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('drink_money', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tips', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bonus_money', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('user_key', 'table_key', 'date_key', 'time_key')
    )
    op.create_table('time_dimension',
    sa.Column('time_key', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('am_pm', sa.String(length=2), nullable=False),
    sa.Column('time_of_day', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('time_key')
    )
    op.create_table('user_dimension',
    sa.Column('user_key', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('user_key')
    )
    with op.batch_alter_table('user_dimension', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_dimension_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_dimension_username'), ['username'], unique=True)

    op.create_table('poker_table_dimension',
    sa.Column('table_key', sa.Integer(), nullable=False),
    sa.Column('room_key', sa.Integer(), nullable=False),
    sa.Column('max_seats', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=50), nullable=False),
    sa.Column('limit_type', sa.String(length=50), nullable=False),
    sa.Column('small_blind', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('big_blind', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_buy_in', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_buy_in', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dealer_ante', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['room_key'], ['room_dimension.room_key'], ),
    sa.PrimaryKeyConstraint('table_key')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.drop_index('ix_user_username')

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('player_key', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('player_key')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_username', ['username'], unique=1)
        batch_op.create_index('ix_user_email', ['email'], unique=1)

    op.drop_table('poker_table_dimension')
    with op.batch_alter_table('user_dimension', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_dimension_username'))
        batch_op.drop_index(batch_op.f('ix_user_dimension_email'))

    op.drop_table('user_dimension')
    op.drop_table('time_dimension')
    op.drop_table('sessions_fact')
    op.drop_table('room_dimension')
    op.drop_table('date_dimension')
    # ### end Alembic commands ###
